### ISSUE TITLE
Error when install the dependencies

### ISSUE THREAD

**Issue by linhlpv** [t6-thu/H2O#1]
Hi,

Thank you for your amazing works. 
I am running your code and having an error when installing the dependencies. 
In particular, when I run the command  `pip install -r requirements.txt,` I got an error 
```
ERROR: Could not find a version that satisfies the requirement dm-control==0.0.412862961 (from versions: 0.0.286587932, 0.0.286955599, 0.0.288398964, 0.0.288483845, 0.0.295778102, 0.0.300771433, 0.0.312466143, 0.0.318037100, 0.0.318066097, 0.0.319497192, 0.0.322773188, 0.0.355168290, 0.0.364896371, 0.0.403778684, 0.0.423341706, 0.0.425341097, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.3.post1, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.0.9, 1.0.10, 1.0.11, 1.0.12, 1.0.13, 1.0.14)
ERROR: No matching distribution found for dm-control==0.0.412862961
```

I have checked that there is no dm-control version that match with this version too. 
Could you please check and help me with installing the dependences.
Thank you a lot and have a great day.

**Comment by t6-thu** [comment]
Thank you for pointing this out. Actually for experiments in H2O paper, we don't have to install dm-control dependencies and I have already removed relevant packages from requirement.txt.

**Comment by t6-thu** [comment]
If you want to try H2O on dm-control tasks, you can install a feasible version at your need.

**Comment by linhlpv** [comment]
Hi @t6-thu , thanks for your reply. I have solved the issue.
