### ISSUE TITLE
Ask about the learned target dynamics

### ISSUE THREAD

**Issue by linhlpv** [t6-thu/H2O#3]
Hi @t6-thu,

Thank you for your amazing work. I am using your code for my work.
When I read your source code, I couldn't find the learned target dynamics as you mentioned in your paper H2O.
Specifically, at the line https://github.com/t6-thu/H2O/blob/bc98dc0be2b2c6bae6588d02ddc94917fa6eb6a5/SimpleSAC/sim2real_sac_main.py#L161, I see that you just pass the None as the dynamics and follows by that, when you compute kl divergence, you create the target next state by adding some noise (https://github.com/t6-thu/H2O/blob/bc98dc0be2b2c6bae6588d02ddc94917fa6eb6a5/SimpleSAC/sim2real_sac.py#L429).

I don't know whether I understood wrong or it was a specific choice of you. Could you please help me with this issue?

Thank you so much.
Best, 
Linh

**Comment by t6-thu** [comment]
During the early stage of the developing process, we had once devised one version of H2O with learned dynamics model but we finally discarded it. So the argument "dynamics_model" is actually unused. In the code snippet, we instead adopt using a normal distribution as simulation dynamics to obtain the simulated next state given a state-action pair from the simulation replay buffer. Please refer to the detailed description in section 4.4 of the paper. We found this approximation sufficiently effective and don't have to implement a learned dynamics into the algorithm.

**Comment by linhlpv** [comment]
Hi @t6-thu,

Thanks for your reply. I have checked the paper.
I have one question that in section 4.4, does the Gaussian distribution $\mathcal{N}(s', \hat{\sum}_{\mathcal{D}}$ refer to the distribution of $s'$ in the dataset $\mathcal{D}$ and not the conditional distribution of $s'$ given $s, a$ in the dataset $\mathcal{D}$? 
![image](https://github.com/t6-thu/H2O/assets/33130456/f19bdf71-7262-4d0c-9b42-5acc3664b3e5)
Could you help me with this?

Thank you.

**Comment by t6-thu** [comment]
The mean values $s'$ are from the simulation transitions while we set the deviation values with the covariance matrix calculated from the real dataset. We have omitted to mention the default fact that the the next state $s'$ is in the same transition with the state-action pair $(s,a)$ sampled from the simulation, when estimating $u(s,a)$ corresponding to that state-action pair.

**Comment by t6-thu** [comment]
Literally, the distribution should concisely be $\mathcal{N}(s',\hat{\Sigma_{\mathcal{D}}}\mid s,a)$ and that is what we inplemented.

**Comment by linhlpv** [comment]
Yub. I have checked the code? Is the ```self.std``` in  the line https://github.com/t6-thu/H2O/blob/bc98dc0be2b2c6bae6588d02ddc94917fa6eb6a5/SimpleSAC/sim2real_sac.py#L82   the coveriance matrix $\hat{\sum}_{\mathcal{D}}$ for each $s, a$. 
I was confused cause I saw that in the line https://github.com/t6-thu/H2O/blob/bc98dc0be2b2c6bae6588d02ddc94917fa6eb6a5/SimpleSAC/mixed_replay_buffer.py#L59, it seems like std was computed for every state in the dataset and not for the conditional distribution.

Thank you.

**Comment by t6-thu** [comment]
yeah, you are right. The std is just a rough but effective approximation while the mean is related to the specific transition.

**Comment by linhlpv** [comment]
yub. Thank you for clarifying that.
